export const ROUTES = {
  home: "/",
  first: "/first",
  concept: "/concept",
  treatments: "/treatments",
  treatmentSlug: (slug: string) => `/treatments/${slug}`,
  symptoms: "/symptoms",
  symptomSlug: (slug: string) => `/symptoms/${slug}`,
  sports: "/sports",
  trafficAccident: "/traffic-accident",
  price: "/price",
  flow: "/flow",
  voice: "/voice",
  staff: "/staff",
  access: "/access",
  column: "/column",
  columnSlug: (slug: string) => `/column/${slug}`,
  faq: "/faq",
  reservation: "/reservation",
  contact: "/contact",
  privacy: "/privacy",
  line: "https://lin.ee/XXXXXXX",
  googleMap: "https://maps.google.com/?q=フリオ天神整骨院",
} as const;
